### ISSUE TITLE
hivelytracker segfaults on FreeBSD

### ISSUE THREAD

**Issue by ehaupt** [pete-gordon/hivelytracker#35]
I built hivelytracker on FreeBSD. Unfortunately it immediately segfaults with:

```console
$ hivelytracker 
SDL says: Fragment size must be a power of two
Segmentation fault (core dumped)
```

```console
$ gdb -f hivelytracker
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...(no debugging symbols found)...
(gdb) r
Starting program: /usr/local/bin/hivelytracker 
SDL says: Fragment size must be a power of two

Program received signal SIGSEGV, Segmentation fault.
0x0000000803928e43 in TTF_SizeUNICODE () from /usr/local/lib/libSDL_ttf-2.0.so.0
Current language:  auto; currently minimal
(gdb) bt
#0  0x0000000803928e43 in TTF_SizeUNICODE () from /usr/local/lib/libSDL_ttf-2.0.so.0
#1  0x0000000803928df1 in TTF_SizeText () from /usr/local/lib/libSDL_ttf-2.0.so.0
#2  0x000000000040686e in ?? ()
#3  0x000000000040aae0 in ?? ()
#4  0x000000000040c341 in ?? ()
#5  0x000000000042507f in ?? ()
#6  0x0000000000402e3b in ?? ()
#7  0x0000000000402495 in ?? ()
#8  0x0000000800650000 in ?? ()
#9  0x0000000000000000 in ?? ()
```

```console
$ uname -a
FreeBSD wiggles.local 11.2-RELEASE-p5 FreeBSD 11.2-RELEASE-p5 #0: Tue Nov 27 09:33:52 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

How to repeat:
https://github.com/ehaupt/ports-wip/tree/master/ports/audio/hivelytracker

**Comment by ehaupt** [comment]
```console
$ ldd $(which hivelytracker)
/usr/local/bin/hivelytracker:
	libm.so.5 => /lib/libm.so.5 (0x80084e000)
	libSDL-1.2.so.0 => /usr/local/lib/libSDL-1.2.so.0 (0x800a7b000)
	libgtk-x11-2.0.so.0 => /usr/local/lib/libgtk-x11-2.0.so.0 (0x800e00000)
	libgdk-x11-2.0.so.0 => /usr/local/lib/libgdk-x11-2.0.so.0 (0x801449000)
	libpangocairo-1.0.so.0 => /usr/local/lib/libpangocairo-1.0.so.0 (0x8016ff000)
	libatk-1.0.so.0 => /usr/local/lib/libatk-1.0.so.0 (0x80190c000)
	libcairo.so.2 => /usr/local/lib/libcairo.so.2 (0x801b37000)
	libthr.so.3 => /lib/libthr.so.3 (0x801e5e000)
	libgdk_pixbuf-2.0.so.0 => /usr/local/lib/libgdk_pixbuf-2.0.so.0 (0x802086000)
	libgio-2.0.so.0 => /usr/local/lib/libgio-2.0.so.0 (0x8022a9000)
	libpangoft2-1.0.so.0 => /usr/local/lib/libpangoft2-1.0.so.0 (0x80263c000)
	libpango-1.0.so.0 => /usr/local/lib/libpango-1.0.so.0 (0x802852000)
	libgobject-2.0.so.0 => /usr/local/lib/libgobject-2.0.so.0 (0x802aa0000)
	libglib-2.0.so.0 => /usr/local/lib/libglib-2.0.so.0 (0x802cea000)
	libintl.so.8 => /usr/local/lib/libintl.so.8 (0x803001000)
	libfontconfig.so.1 => /usr/local/lib/libfontconfig.so.1 (0x80320c000)
	libfreetype.so.6 => /usr/local/lib/libfreetype.so.6 (0x803453000)
	libSDL_image-1.2.so.0 => /usr/local/lib/libSDL_image-1.2.so.0 (0x803709000)
	libSDL_ttf-2.0.so.0 => /usr/local/lib/libSDL_ttf-2.0.so.0 (0x803926000)
	libz.so.6 => /lib/libz.so.6 (0x803b2d000)
	libX11.so.6 => /usr/local/lib/libX11.so.6 (0x803d45000)
	libc.so.7 => /lib/libc.so.7 (0x804084000)
	libvgl.so.6 => /usr/lib/libvgl.so.6 (0x804440000)
	libaa.so.1 => /usr/local/lib/libaa.so.1 (0x80464a000)
	libusbhid.so.4 => /usr/lib/libusbhid.so.4 (0x804862000)
	libXrender.so.1 => /usr/local/lib/libXrender.so.1 (0x804a66000)
	libXinerama.so.1 => /usr/local/lib/libXinerama.so.1 (0x804c6f000)
	libXi.so.6 => /usr/local/lib/libXi.so.6 (0x804e71000)
	libXrandr.so.2 => /usr/local/lib/libXrandr.so.2 (0x80507f000)
	libXcursor.so.1 => /usr/local/lib/libXcursor.so.1 (0x805289000)
	libXext.so.6 => /usr/local/lib/libXext.so.6 (0x805494000)
	libgmodule-2.0.so.0 => /usr/local/lib/libgmodule-2.0.so.0 (0x8056a5000)
	libXcomposite.so.1 => /usr/local/lib/libXcomposite.so.1 (0x8058a8000)
	libXdamage.so.1 => /usr/local/lib/libXdamage.so.1 (0x805aaa000)
	libXfixes.so.3 => /usr/local/lib/libXfixes.so.3 (0x805cac000)
	libpixman-1.so.0 => /usr/local/lib/libpixman-1.so.0 (0x805eb1000)
	libEGL.so.1 => /usr/local/lib/libEGL-NVIDIA.so.1 (0x80615b000)
	libpng16.so.16 => /usr/local/lib/libpng16.so.16 (0x80645d000)
	libxcb-shm.so.0 => /usr/local/lib/libxcb-shm.so.0 (0x806698000)
	libxcb.so.1 => /usr/local/lib/libxcb.so.1 (0x80689a000)
	libxcb-render.so.0 => /usr/local/lib/libxcb-render.so.0 (0x806ac0000)
	libGL.so.1 => /usr/local/lib/libGL-NVIDIA.so.1 (0x806ccd000)
	libffi.so.6 => /usr/local/lib/libffi.so.6 (0x806ff8000)
	libiconv.so.2 => /usr/local/lib/libiconv.so.2 (0x8071ff000)
	libpcre.so.1 => /usr/local/lib/libpcre.so.1 (0x8074fa000)
	libharfbuzz.so.0 => /usr/local/lib/libharfbuzz.so.0 (0x80777d000)
	libfribidi.so.0 => /usr/local/lib/libfribidi.so.0 (0x807a41000)
	libexpat.so.1 => /usr/local/lib/libexpat.so.1 (0x807c57000)
	libbz2.so.4 => /usr/lib/libbz2.so.4 (0x807e82000)
	libncurses.so.8 => /lib/libncurses.so.8 (0x808096000)
	librt.so.1 => /usr/lib/librt.so.1 (0x8082eb000)
	libnvidia-glsi.so.1 => /usr/local/lib/libnvidia-glsi.so.1 (0x8084f1000)
	libXau.so.6 => /usr/local/lib/libXau.so.6 (0x808776000)
	libXdmcp.so.6 => /usr/local/lib/libXdmcp.so.6 (0x808979000)
	libnvidia-tls.so.1 => /usr/local/lib/libnvidia-tls.so.1 (0x808b7e000)
	libnvidia-glcore.so.1 => /usr/local/lib/libnvidia-glcore.so.1 (0x808e00000)
	libgraphite2.so.3 => /usr/local/lib/libgraphite2.so.3 (0x80b86e000)
	libc++.so.1 => /usr/lib/libc++.so.1 (0x80ba97000)
	libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x80bd65000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x80bf84000)
```

**Comment by ehaupt** [comment]
Close inactive issue.
